version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: team-wels-db
    environment:
      POSTGRES_DB: teamwels
      POSTGRES_USER: teamwels
      POSTGRES_PASSWORD:  teamwels
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - team-wels-network

  backend:
    build: ./backend/backend
    container_name: team-wels-backend
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/teamwels
      QUARKUS_DATASOURCE_USERNAME: teamwels
      QUARKUS_DATASOURCE_PASSWORD: teamwels
    depends_on:
      - postgres
    networks:
      - team-wels-network

volumes:
  postgres-data:

networks:
  team-wels-network:
    driver:  bridge